version: '3.8'

services:
  libretranslate:
    image: libretranslate/libretranslate:latest
    ports:
      - "5001:5000"
    environment:
      - LT_LOAD_ONLY=en,es,fr,de,it,ko,ja,th

  proxy:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - libretranslate
